# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pfuse}
  s.version = "0.7.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Turnbull", "Kyle Maxwell"]
  s.date = %q{2010-02-26}
  s.description = %q{Gemified}
  s.email = %q{dsturnbull@me.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "API.txt",
     "Changes.txt",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "ext/extconf.rb",
     "ext/fusefs_fuse.c",
     "ext/fusefs_fuse.h",
     "ext/fusefs_lib.c",
     "ext/fusefs_lib.h",
     "hello.sh",
     "lib/fusefs.rb",
     "pfuse.gemspec",
     "sample/demo.rb",
     "sample/dictfs.rb",
     "sample/hello.rb",
     "sample/openurifs.rb",
     "sample/railsfs.rb",
     "sample/sqlfs.rb",
     "sample/yamlfs.rb",
     "test/fusefs_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/dsturnbull/pfuse}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{fusefs}
  s.test_files = [
    "test/fusefs_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

